# Generated by Django 4.2.4 on 2023-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=50)),
                ('team_no', models.CharField(default='Team 1', max_length=100)),
                ('participant_1_Name', models.CharField(max_length=50)),
                ('participant_1_class', models.CharField(max_length=100, null=True)),
                ('participant_1_rollno', models.CharField(max_length=100, null=True)),
                ('participant_1_contactno', models.CharField(max_length=100, null=True)),
                ('participant_2_Name', models.CharField(max_length=50)),
                ('participant_2_class', models.CharField(max_length=100, null=True)),
                ('participant_2_rollno', models.CharField(max_length=100, null=True)),
                ('participant_2_contactno', models.CharField(max_length=100, null=True)),
                ('participant_3_Name', models.CharField(max_length=50, null=True)),
                ('participant_3_class', models.CharField(max_length=100, null=True)),
                ('participant_3_rollno', models.CharField(max_length=100, null=True)),
                ('participant_3_contactno', models.CharField(max_length=100, null=True)),
                ('participant_4_Name', models.CharField(max_length=50, null=True)),
                ('participant_4_class', models.CharField(max_length=100, null=True)),
                ('participant_4_rollno', models.CharField(max_length=100, null=True)),
                ('participant_4_contactno', models.CharField(max_length=100, null=True)),
                ('participant_5_Name', models.CharField(max_length=50, null=True)),
                ('participant_5_class', models.CharField(max_length=100, null=True)),
                ('participant_5_rollno', models.CharField(max_length=100, null=True)),
                ('participant_5_contactno', models.CharField(max_length=100, null=True)),
                ('participant_6_Name', models.CharField(max_length=50, null=True)),
                ('participant_6_class', models.CharField(max_length=100, null=True)),
                ('participant_6_rollno', models.CharField(max_length=100, null=True)),
                ('participant_6_contactno', models.CharField(max_length=100, null=True)),
                ('participant_7_Name', models.CharField(max_length=50, null=True)),
                ('participant_7_class', models.CharField(max_length=100, null=True)),
                ('participant_7_rollno', models.CharField(max_length=100, null=True)),
                ('participant_7_contactno', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
