# Generated by Django 4.2.5 on 2023-09-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_name_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='gaming_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='it_manager_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='it_quiz_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='short_film_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='treasure_hunt_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
        migrations.AlterField(
            model_name='web_designing_details',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.team_name_list'),
        ),
    ]
