# Generated by Django 4.2.4 on 2023-09-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team_leader1',
        ),
    ]
