# Generated by Django 4.2.4 on 2023-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_customuser_team_leader1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=50)),
                ('team_no', models.CharField(default='Team 1', max_length=100)),
                ('participant_name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=15)),
            ],
        ),
    ]
