# Generated by Django 4.2.4 on 2023-09-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_designing_details',
            name='team_no',
            field=models.CharField(choices=[('Team 1', '1'), ('Team 2', '2'), ('Team 3', '3'), ('Team 4', '4'), ('Team 5', '5'), ('Team 6', '6')], max_length=100),
        ),
    ]
