# Generated by Django 4.2.4 on 2023-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_web_designing_details_team_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_designing_details',
            name='event_name',
            field=models.CharField(default='Web Designing', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='web_designing_details',
            name='team_no',
            field=models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2'), ('3', 'Team 3'), ('4', 'Team 4'), ('5', 'Team 5'), ('6', 'Team 6')], max_length=100),
        ),
    ]
