# Generated by Django 4.2.4 on 2023-09-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_web_designing_details_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming_details',
            name='participant_5_Name',
        ),
        migrations.RemoveField(
            model_name='gaming_details',
            name='participant_5_class',
        ),
        migrations.RemoveField(
            model_name='gaming_details',
            name='participant_5_contactno',
        ),
        migrations.RemoveField(
            model_name='gaming_details',
            name='participant_5_rollno',
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_2_Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_2_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_2_contactno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_2_rollno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_3_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_3_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_3_contactno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_3_rollno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_4_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_4_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_4_contactno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_4_rollno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_5_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_5_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_5_contactno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='it_manager_details',
            name='participant_5_rollno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='event_name',
            field=models.CharField(default='Coding', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='participant_1_Name',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='participant_1_class',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='participant_1_contactno',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='participant_1_rollno',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='coding_details',
            name='team_no',
            field=models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2'), ('3', 'Team 3'), ('4', 'Team 4'), ('5', 'Team 5'), ('6', 'Team 6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gaming_details',
            name='event_name',
            field=models.CharField(default='Gaming', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='gaming_details',
            name='team_no',
            field=models.CharField(default='1', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='event_name',
            field=models.CharField(default='Hackathon', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_1_Name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_1_class',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_1_contactno',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_1_rollno',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_2_Name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_2_class',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_2_contactno',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='participant_2_rollno',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='hackathon_details',
            name='team_no',
            field=models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2'), ('3', 'Team 3'), ('4', 'Team 4'), ('5', 'Team 5'), ('6', 'Team 6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='it_manager_details',
            name='event_name',
            field=models.CharField(default='IT Manager', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='it_manager_details',
            name='team_no',
            field=models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2'), ('3', 'Team 3'), ('4', 'Team 4'), ('5', 'Team 5'), ('6', 'Team 6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='it_quiz_details',
            name='event_name',
            field=models.CharField(default='IT Quiz', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='it_quiz_details',
            name='team_no',
            field=models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2'), ('3', 'Team 3'), ('4', 'Team 4'), ('5', 'Team 5'), ('6', 'Team 6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='treasure_hunt_details',
            name='event_name',
            field=models.CharField(default='Treasure Hunt', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='treasure_hunt_details',
            name='team_no',
            field=models.CharField(default='1', editable=False, max_length=100),
        ),
    ]
